//project
export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST'
export const SET_PROJECT_PARAMS = 'SET_PROJECT_PARAMS'

export const GET_USERS = 'GET_USERS'

//customers
export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST'

//roof-rental
export const FETCH_ROOF_RENTAL_UNIT_REQUEST = 'FETCH_ROOF_RENTAL_UNIT_REQUEST'
